# Generated by Django 4.0.2 on 2022-09-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AAGardens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('Contact_Id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=250)),
                ('Company', models.CharField(max_length=500)),
                ('MobileNumber', models.CharField(max_length=100)),
                ('Message', models.TextField()),
            ],
        ),
    ]
